version: '2.1'

services:
  challenge-charlie:
    image: challenge-charlie
    build: .
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm start